### ISSUE TITLE
Swift Package Manager Errors

### ISSUE THREAD

**Issue by sschizas** [Workable/swift-error-handler#3]
Hi, 

I am trying to add ErrorHandler as a dependency in my project using SPM (XCode 11.3.1). If I select an explicit version, SPM throws the following error:
```
The package dependency graph can not be resolved; unable find any available tag for the following requirements:
```
If I select any version on the master branch, SPM throws this error:
```
: package at 'https://github.com/Workable/swift-error-handler' @ f16953652e9c64a75215ccf740e9e4f5bbfc5ba8 is using Swift tools version 3.1.0 which is no longer supported; consider using '// swift-tools-version:5.1' to specify the current tools version

```

Any thoughts?

PS: Also, I would suggest bumping project's version to 1.0 as it is stable.

**Comment by gtsifrikas** [comment]
We'll get around to doing it when we have available time but until then we're open to contributions. :)
